apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
      - name: traefik
        image: traefik:1.3
        args:
        - --web
        - --kubernetes
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 40Mi
          requests:
            cpu: 250m
            memory: 40Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
  name: traefik
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: traefik
  type: LoadBalancer
