---
version: 2
jobs:
  lint_test:
    docker:
      - image: previousnext/golang:1.8
    working_directory: /go/src/github.com/previousnext/m8s
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run linting
          command: make lint
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
  build:
    docker:
      - image: previousnext/golang:1.8
    working_directory: /go/src/github.com/previousnext/m8s
    steps:
      - checkout
      - run:
          name: Compile binaries
          command: make build
      - persist_to_workspace:
          root: .
          paths:
            - bin
  release:
    docker:
      - image: previousnext/golang:1.8
    working_directory: /go/src/github.com/previousnext/m8s
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Push release binary to github
          command: ghr -u previousnext "$(git describe --tag --exact)" ./bin/

workflows:
  version: 2
  everything:
    jobs:
      - lint_test
      - build
      - release:
          requires:
            - lint_test
            - build
          filters:
            # Only run for version tags. Never for branches.
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
