apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:      pr
  namespace: kube-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: pr
    spec:
      containers:
        - name:  api
          image: previousnext/pr:4f3c96a
          env:
            - name:  AUTH_BACKEND
              value: "github"
            - name:  TOKEN
              value: "6dkpeI1CvP1xDhg6"
            - name:  NAMESPACE
              value: "kube-system"
            - name:  TLS_CERT
              value: "/etc/tls/cert.crt"
            - name:  TLS_KEY
              value: "/etc/tls/cert.key"
          resources:
            limits:
              cpu:    100m
              memory: 40Mi
            requests:
              cpu:    100m
              memory: 40Mi
          volumeMounts:
            - name:      tls
              mountPath: "/etc/tls"
              readOnly:  true
      volumes:
        - name: tls
          secret:
            secretName: pr
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: pr
type: Opaque
data:
  cert.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQekNDQkNlZ0F3SUJBZ0lUQnFtaVNISUha
    VGVDeTRremR6bXRhOVlvYURBTkJna3Foa2lHOXcwQkFRc0YKQURDQnRURUxNQWtHQTFVRUJoTUNW
    Vk14RVRBUEJnTlZCQWdUQ0Vsc2JHbHViMmx6TVJBd0RnWURWUVFIRXdkRAphR2xqWVdkdk1TRXdI
    d1lEVlFRS0V4aFVjblZ6ZEhkaGRtVWdTRzlzWkdsdVozTXNJRWx1WXk0eFBUQTdCZ05WCkJBTVRO
    RlJ5ZFhOMGQyRjJaU0JQY21kaGJtbDZZWFJwYjI0Z1ZtRnNhV1JoZEdsdmJpQlRTRUV5TlRZZ1Ew
    RXMKSUV4bGRtVnNJREV4SHpBZEJna3Foa2lHOXcwQkNRRVdFR05oUUhSeWRYTjBkMkYyWlM1amIy
    MHdIaGNOTVRjdwpNVE13TVRZMU1UTTFXaGNOTVRnd01qRTBNakkxTVRNMVdqQnhNUmd3RmdZRFZR
    UUREQThxTG1Oa0xuQnVlQzVqCmIyMHVZWFV4SFRBYkJnTlZCQW9URkZCeVpYWnBiM1Z6VG1WNGRD
    QlFkSGtnVEhSa01ROHdEUVlEVlFRSEV3WlQKZVdSdVpYa3hHREFXQmdOVkJBZ1REMDVsZHlCVGIz
    VjBhQ0JYWVd4bGN6RUxNQWtHQTFVRUJoTUNRVlV3Z2dFaQpNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0
    SUJEd0F3Z2dFS0FvSUJBUUMra1hsL1pTMHVtMjhUald5YWxuY2VtTTV3CkpPUlM2MnFGcFJTME9Q
    UytYUGU4ajJ6VHMyQ09iOStYVmM3ZXNBZDdjNzJiSVgxZStiUnNRZ2l4RHg4bzJ4VnYKKzUvaVdI
    SXlQT21HZ0lkY2NacUphNGpXZnVpbVhwZnJFYlRxNW5ZR0tMbnJIdWVaU085RXE5Z3R5YXZtbXB4
    aApscDdGRnB5aXBIcTloU2lSbjc1UDhrRThqSGJ2UDZJSWZKdnJpandwejdocXRYRDlPODBKY3Vu
    bFc2REgzWjhSCjY3SWVDKzU3cGg3dVV5V1VxeFlNWUo5NVlCMEM2Wmg2ajBOZ1ZFRUpHYjVCaGpV
    cGV5Q3V1UkZpUDE2U0szRTkKMGpHajFSd21Qd2FsNW1TZll2akd3NUFVMUNlMURzcGI3dEZKTFg5
    SWVUVEtPQW1HUEZtbWNKT1IwUVY1QWdNQgpBQUdqZ2dHSk1JSUJoVEFNQmdOVkhSTUJBZjhFQWpB
    QU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlZIU1VFCkZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZ
    QkJRVUhBd0V3SFFZRFZSME9CQllFRkNBM1ZUejJXbW5iL1IrckFPRnMKV1dhcUZhMk5NQjhHQTFV
    ZEl3UVlNQmFBRk1yT0hSZ0RkeDRjODN4WXNwcHdxQWlBRnZTdU1EOEdBMVVkSUFRNApNRFl3TkFZ
    R1o0RU1BUUlDTUNvd0tBWUlLd1lCQlFVSEFnRVdIR2gwZEhCek9pOHZjM05zTG5SeWRYTjBkMkYy
    ClpTNWpiMjB2UTBFd0dnWURWUjBSQkJNd0VZSVBLaTVqWkM1d2JuZ3VZMjl0TG1GMU1EWUdBMVVk
    SHdRdk1DMHcKSzZBcG9DZUdKV2gwZEhBNkx5OWpjbXd1ZEhKMWMzUjNZWFpsTG1OdmJTOVBWa05C
    TWw5TU1TNWpjbXd3Y1FZSQpLd1lCQlFVSEFRRUVaVEJqTUNZR0NDc0dBUVVGQnpBQmhocG9kSFJ3
    T2k4dmIyTnpjQzUwY25WemRIZGhkbVV1ClkyOXRMekE1QmdnckJnRUZCUWN3QW9ZdGFIUjBjRG92
    TDNOemJDNTBjblZ6ZEhkaGRtVXVZMjl0TDJsemMzVmwKY25NdlQxWkRRVEpmVERFdVkzSjBNQTBH
    Q1NxR1NJYjNEUUVCQ3dVQUE0SUJBUURRQ3R1RkhBbCtzalhZdVZySQoyWFE0NndTR216RGRqaUJW
    QkdlQjFxSFc2NU5KaVJXdEN0Vld5dGpWWGlWUmNGa0hWbkZjekhWRmVyZHNycDRJCm5jQ0F6VGJp
    Tno3am9zd3diMWpScmFFa0Z5dmFLWlhQd3VkRTRXWmtRSVhrT0JQcTArMTVWNWsxT3VSbGwxQzEK
    TFNZTmlHUzhnNS9lVTA0QjczaThSOWY5dVI5blgvODNMa2JIV3hTUDhWelYzdjZnemlnTmprblFP
    dUZ2L2hubwpJUGh6TVM0TXJQNk81WU9QSVI0dzdvMkVneTYxZGkxN0p0Vno4RHVyLzZmLzNwUVBU
    Z3poS05ZK2xDQ0kxVVM1CmZLMy9xTVhBaUtsV3NPaWNKUHlMQXZISU43TXhzZXpndWFGM054d3Qv
    VS9KYTVDbWlQaTl2SjcyaGE3ZDVPak0KS2lmagotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0t
    LS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFL1RDQ0ErV2dBd0lCQWdJUVN5eG1SdlEwZDF0
    bjN6U2dUZFVFNWpBTkJna3Foa2lHOXcwQkFRc0ZBREJJCk1Rc3dDUVlEVlFRR0V3SlZVekVnTUI0
    R0ExVUVDaE1YVTJWamRYSmxWSEoxYzNRZ1EyOXljRzl5WVhScGIyNHgKRnpBVkJnTlZCQU1URGxO
    bFkzVnlaVlJ5ZFhOMElFTkJNQjRYRFRFME1UQXdNVEU1TWpJek5sb1hEVEkwTURreQpPREU1TWpJ
    ek5sb3dnYlV4Q3pBSkJnTlZCQVlUQWxWVE1SRXdEd1lEVlFRSUV3aEpiR3hwYm05cGN6RVFNQTRH
    CkExVUVCeE1IUTJocFkyRm5iekVoTUI4R0ExVUVDaE1ZVkhKMWMzUjNZWFpsSUVodmJHUnBibWR6
    TENCSmJtTXUKTVQwd093WURWUVFERXpSVWNuVnpkSGRoZG1VZ1QzSm5ZVzVwZW1GMGFXOXVJRlpo
    Ykdsa1lYUnBiMjRnVTBoQgpNalUySUVOQkxDQk1aWFpsYkNBeE1SOHdIUVlKS29aSWh2Y05BUWtC
    RmhCallVQjBjblZ6ZEhkaGRtVXVZMjl0Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThB
    TUlJQkNnS0NBUUVBNDlPb2hsSkhCSi9qdWlRVG1pYk8KUzI4cEh2Q0NwMWJQT2M2ZWxRNjJEQ1lF
    L0ExNEpYVXRJOHlhVWM5bkZqaDZkTnpSN0tqRlBFcS9xRHBsUWw3ZgoxVHZoNWlmQk5OUDJ3UTZl
    ODIwVFdsUE80SGhSLzVnNCszaUZtSjFON2tGcnhEcDEvUDhlMys5bGNKc1hja1hDCnRmRmtROXNs
    b2dKcW5hQ3NpcGdkckg0Z1FoaWNGQUw1WXFIdzJBS2ZjdFpMU1BweGhJM3hJU01WL2xJUXdaUFcK
    STIyMjF2OUFMY2tva2g1cFc2ZFRLOHg4eU5VVXllMXp0NW1zV3pxdW5mQmpWWVZVajUvTFh1NDZo
    Uzk5TWZ4dQo4MEFSSlJ5SHNYSXVIYk16d1ZYR3FLVlBaZktBZEhCbDVlM0VsQ2pOd055K0hnaTA5
    dlM3UG9BVWhqQ2Yvd2JPCm5RSURBUUFCbzRJQmN6Q0NBVzh3RWdZRFZSMFRBUUgvQkFnd0JnRUIv
    d0lCQURBZEJnTlZIUTRFRmdRVXlzNGQKR0FOM0hoenpmRml5bW5Db0NJQVc5SzR3RGdZRFZSMFBB
    UUgvQkFRREFnR0dNRWdHQTFVZElBUkJNRDh3UFFZUApLd1lCQkFHQjdSZ0RBd01EQkFRRE1Db3dL
    QVlJS3dZQkJRVUhBZ0VXSEdoMGRIQnpPaTh2YzNOc0xuUnlkWE4wCmQyRjJaUzVqYjIwdlEwRXdN
    Z1lEVlIwZkJDc3dLVEFub0NXZ0k0WWhhSFIwY0RvdkwyTnliQzUwY25WemRIZGgKZG1VdVkyOXRM
    MU5VUTBFdVkzSnNNR3dHQ0NzR0FRVUZCd0VCQkdBd1hqQWxCZ2dyQmdFRkJRY3dBWVlaYUhSMApj
    RG92TDI5amMzQXVkSEoxYzNSM1lYWmxMbU52YlRBMUJnZ3JCZ0VGQlFjd0FvWXBhSFIwY0Rvdkwz
    TnpiQzUwCmNuVnpkSGRoZG1VdVkyOXRMMmx6YzNWbGNuTXZVMVJEUVM1amNuUXdIUVlEVlIwbEJC
    WXdGQVlJS3dZQkJRVUgKQXdJR0NDc0dBUVVGQndNQk1COEdBMVVkSXdRWU1CYUFGRUl5dGhiNkJQ
    MytYVXQ2dy8zM1RFQWRXa092TUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk4vUWI2eDVWU1FI
    SXQvRnF2WEFramZDSTdqd1hHelJveFRoYXZVcXYwCnBKcjFhelhLdjJMMnllOVNsNE9DcWlESFo4
    WkpaL1oxOUFlMXl2R1RwRysrME81ZFdUSFo4cXkvSlNqMTdNZzEKdldpZWZWcEpLdGtZZmx6aEM5
    QjkvZUIzUXVLVlRSS0RxbTFaQzlrYm0zTVdPd3RuRU93NFdVUldTMVgydjRIdgoyQUphWGUxMVpS
    cWp4Ny9jNlU1MHRZcDNlVnBSREN3N2JPSVhSZmZMRzBvaWJoakhpRXU4ZGdxN0trVFNyeDltClFG
    UzZUMng5R0xpSktoajJtRWZQdUdyNzNUZkJQeUtzUkJ5bU9wRzY3TFRoS1Zud29VZkgzcGdoQTZW
    a1pwNVoKMVZtNkFjRG0rZWVsZjVYUHZadE52ZTRldkxWUFl1ZUEzVG1HeXhYaDFtMmQKLS0tLS1F
    TkQgQ0VSVElGSUNBVEUtLS0tLQ==
  cert.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktrd2dnU2xBZ0VBQW9JQkFRQytrWGwvWlMwdW0yOFQKald5YWxuY2VtTTV3Sk9SUzYycUZw
    UlMwT1BTK1hQZThqMnpUczJDT2I5K1hWYzdlc0FkN2M3MmJJWDFlK2JScwpRZ2l4RHg4bzJ4VnYr
    NS9pV0hJeVBPbUdnSWRjY1pxSmE0aldmdWltWHBmckViVHE1bllHS0xuckh1ZVpTTzlFCnE5Z3R5
    YXZtbXB4aGxwN0ZGcHlpcEhxOWhTaVJuNzVQOGtFOGpIYnZQNklJZkp2cmlqd3B6N2hxdFhEOU84
    MEoKY3VubFc2REgzWjhSNjdJZUMrNTdwaDd1VXlXVXF4WU1ZSjk1WUIwQzZaaDZqME5nVkVFSkdi
    NUJoalVwZXlDdQp1UkZpUDE2U0szRTkwakdqMVJ3bVB3YWw1bVNmWXZqR3c1QVUxQ2UxRHNwYjd0
    RkpMWDlJZVRUS09BbUdQRm1tCmNKT1IwUVY1QWdNQkFBRUNnZ0VCQUpCdm9pNjBlTEpDak1XOUF2
    dUgzM0VKVUM0ZlNBNnc3Mk9yNHkxVm5lcEsKZkZvbU9zMlp2eTAyRGJtZUI5VXdoZnREbGdubU1D
    ZTBDdE9pbVFQWitqdjFFU0ozREk5NWlkUVo1c1ZTMVVWegp0VFZDazh3L0ZBWkUyOUFHODZDMlcr
    My9JQ3JjbVp6TWNzMFJraC9pSXEvOXIxa24xOTU1Yk82NHkyNnBaajQ0CkMvQUV0YUJvVDdKS242
    ajd4Q1M5UlI0TWJCbHEyWDdDREZnQXNCUEZ4M0VudnVMVUZtMjBsZStsbHdEa29OdWYKOS83YmVi
    cHM2SmgrTW5waklGUStRWjRmVEJhZG5KRFpqMCtmZmZRRzNNT0xiUThVVUk5bGU3L2Z4K0tDVENW
    cwo3djZLVFpNcVYzVW9BcURJTndOSEtOQ2Rrai9CcHNMYXl0R0xSdVJ5aUFFQ2dZRUE5L0dPa1o1
    TXp6RXNha2ljClJSZ1FrQ1Q0Vjg4enZjTGZBODFWMW5aUm5BVy9IN09wQnlJNVhGODZYTEZncHBL
    Zk1rQmw5TzNtUWg3L0FNU1oKQVlmbHFFTjdzdkdpTllwVGE1QVEyd3lDalQzdHc2YVQyakYwaXR5
    RGNRV2VRK0MrRzJkMGdHYTd4a2RFY09DRQo1bXNyM1F5cjJHZ0dabUlmcklaTTJUUkxZUmtDZ1lF
    QXhNS29tQ0d6dCs3Qm5OUDZxTFVLTjJicnNXT2FnWDdwCkU4OW5kSXk4Y285K0IwQWxtQXkySk9r
    eHk3QUxSRURXRUw1Nm1mQ1VnLzFuTFFEWlRLYXNrOEt2YnBzV0U4QUcKaENIQmFxTmtGZXlXSjlP
    RDhNT0hZL0szMy81N2JQQ21wL1gvNEtZdDdqdkgxZWxjV29ybEtlSU5RTnI2cExuUAoxYXlLQkw4
    YmMyRUNnWUI2anduRkN6VzJlUDBXY0Z2bWYzVzRlcjNUVWRXbXFFdnFxallTODV0MWZ4V3hTdkp6
    ClYwUjVWNDBXd29zZTYzMExydTkyK1oyRzg2RmpOTXJaQ2Q3SXBNcmhjaldYTjQveXJGelltajl5
    SjdsK3E3bUwKOGtSRVc2b1JWUkNkUnR0UjJucW8rWjg1N0lKMU5WWWNPNytMM2JhWUd4dUd3bHdi
    d0tyOTlxNklDUUtCZ1FDTQp5cmwyK282dDY4TlE1QUkxbkMzdVROQVVRN0I0UHdhcTdUc2JFK1Y0
    bUNMWEwxaDNQNGxLU2k4ZWtCN1B2UkV3Ck5BeG9nTlRVeVl0OWtXRHNUMHVvQTZRaW9naWZJMFhH
    WUowVklFdHF3THNGVG4zWDF5SFhMQVBVM1RVV1UvRDgKdUxOYTNhNTZEUDdHbTFCQlhhZnpXMVNl
    ZHRMbzhpaTh2ZFNZNXVMT29RS0JnUUQwMzlFbElEY1B0M2RCL25HdwpNbk5YNDZtQmpBNTJYdm1P
    UURmaFAyVFRXL29yQzZVNGJGa3plVGt3ajBweVZjVk14R3JOcUxJZ1ZpcE9HbVowCk9ORDNicVAx
    Y3o3cnYxekV6Y2dienJmdXhRdzNRaFNiYjV4a0VGOGFxaGRDMDVUdlFBcndPYnRrZEdNZ1ZLaTMK
    RUluazhuUTQyWkt4N2dnOEkxWVNDS3dqREE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: pr
  labels:
    app: pr
spec:
  type: NodePort
  ports:
    - port:     443
      nodePort: 30443
      name:     tls
  selector:
    app: pr
